#!/bin/sh
TMP=/tmp/jsay.wav

echo "$1" | open_jtalk \
-x /var/lib/mecab/dic/open-jtalk/naist-jdic \
-m /usr/share/hts-voice/mei/mei_happy.htsvoice \
-r 1.0 \
-ow $TMP && \
aplay --quiet $TMP
rm -f $TMP
